# Generated by Django 5.1.7 on 2025-04-29 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasic',
            fields=[
                ('emp_code', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.TextField()),
                ('emp_age', models.IntegerField()),
                ('emp_dob', models.DateField(default='2000-01-01')),
                ('emp_comp_email', models.EmailField(max_length=254)),
                ('emp_pers_email', models.EmailField(max_length=254)),
                ('emp_phn_no', models.IntegerField()),
                ('emp_loc', models.TextField()),
                ('emp_cli_name', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeebasic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_name', models.TextField()),
                ('serial_number', models.TextField()),
                ('asset_allocated', models.BooleanField()),
                ('asset_type', models.TextField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop'), ('Other', 'Other')])),
                ('last_upd_date_time', models.DateTimeField(auto_now=True)),
                ('emp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('resign_id', models.IntegerField(primary_key=True, serialize=False)),
                ('res_date', models.DateField()),
                ('last_day', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('pend_from', models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('IT', 'IT'), ('Security', 'Security'), ('Finance', 'Finance')], max_length=10)),
                ('hr_comments', models.TextField()),
                ('emp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.employeebasic')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('suggestions_role', models.TextField()),
                ('culture', models.TextField()),
                ('valued', models.TextField()),
                ('support', models.TextField()),
                ('leadership', models.IntegerField()),
                ('retention', models.TextField()),
                ('incidents', models.TextField()),
                ('suggestions_company', models.TextField()),
                ('recommend', models.CharField(max_length=3)),
                ('likes', models.TextField()),
                ('experience', models.IntegerField()),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.resignation')),
            ],
        ),
        migrations.CreateModel(
            name='AssetExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='tems.asset')),
                ('assigned_for_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_for_exit', to='tems.resignation')),
            ],
        ),
        migrations.CreateModel(
            name='ResignationExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_to_manager', models.BooleanField(default=False)),
                ('hr_reviewed', models.BooleanField(default=False)),
                ('manager_reviewed', models.BooleanField(default=False)),
                ('manager_approved', models.BooleanField(default=False)),
                ('email_disabled', models.BooleanField(default=False)),
                ('system_access_disabled', models.BooleanField(default=False)),
                ('it_clearance', models.BooleanField(default=False)),
                ('security_clearance', models.BooleanField(default=False)),
                ('final_hr_approved', models.BooleanField(default=False)),
                ('finance_clearance', models.BooleanField(default=False)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='tems.resignation')),
            ],
        ),
    ]
