# Generated by Django 5.1.7 on 2025-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0002_assetextras_returned_employeebasic_emp_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='manager_comments',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
