# Generated by Django 5.1.7 on 2025-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0003_resignation_manager_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='finance_comments',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
