# Generated by Django 5.1.7 on 2025-05-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0004_resignation_finance_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignationextras',
            name='forwarded_to_manager',
        ),
    ]
