# Generated by Django 5.1.7 on 2025-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0005_remove_resignationextras_forwarded_to_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationextras',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
