# Generated by Django 5.1.7 on 2025-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0006_resignationextras_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationextras',
            name='final_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resignationextras',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
