# Generated by Django 5.1.7 on 2025-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0007_resignationextras_final_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationextras',
            name='final_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='resignationextras',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
